uploads = []
generated = []

[[outputs]]
id = "6Sj0F3d2NSj5IxcBaDUOp"
uri = "file://shopuz-cpanel-deploy.tar.gz"
type = "unspecified"
title = "ShopUz — cPanel Deployment Package"

[[outputs]]
id = "zhZc82-5ZHD5Ng3dDMnAj"
uri = "file://shopuz-ready.tar.gz"
type = "unspecified"
title = "ShopUz — To'liq tayyor (node_modules bilan, npm kerak emas)"

[[outputs]]
id = "T0KCxtz6WicC50pqJ7cZu"
uri = "file://shopuz-v2.tar.gz"
type = "unspecified"
title = "ShopUz v2 — cPanel/Passenger to’liq tayyor"

[[outputs]]
id = "n6U5g---Y4UP7ucAsqgoY"
uri = "file://shopuz-v3.tar.gz"
type = "unspecified"
title = "ShopUz v3 — To’liq ishlaydigan (test qilingan)"

[[outputs]]
id = "j4nLWtHfKvbSCcbFLCSfW"
uri = "file://shopuz-v4.tar.gz"
type = "unspecified"
title = "ShopUz v4 — Passenger uchun to‘g‘ri sozlangan"

[[outputs]]
id = "a8GNglSO4wXUNPb84V1U-"
uri = "file://shopuz-v5.tar.gz"
type = "unspecified"
title = "ShopUz v5 — 401KB (node_modules siz, CloudLinux uchun to‘g‘ri)"

[[outputs]]
id = "cfacWV7n1EeDxuXiIqPRj"
uri = "file://shopuz-v6.tar.gz"
type = "unspecified"
title = "ShopUz v6 — 315KB (muammo hal qilindi)"
